site_name: OgreInterface Documentation

nav:
  - Home: index.md
  - API: 
      - Generators: generate.md
      - Surfaces: surfaces.md
      - Miller Index Scan: miller.md
      - Utils: utils.md
      - Zur and McGill Algorithm: lattice_match.md
      - Surface Matching:
        - 'surface_match/ionic_surface_matcher.md'
        - 'surface_match/sphere_surface_matcher.md'
      - Score Function:
        - 'score_function/born.md'
        - 'score_function/ewald.md'
        - 'score_function/overlap.md'

plugins:
  - mkdocstrings

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
